name: Sync Fork

on:
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight UTC
  workflow_dispatch:      # Allows manual trigger

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout your fork
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Fetch upstream changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git remote add upstream https://github.com/CE-PhoenixCart/PhoenixCart.git
          git fetch upstream --prune
          for branch in $(git branch -r | grep 'upstream/' | sed 's/upstream\///'); do
            git checkout $branch || git checkout -b $branch upstream/$branch
            git merge upstream/$branch
            git push origin $branch
          done
